In [ ]:
import numpy as np

2.2.6


Creation of numpy arrays from list

In [5]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [21]:
print(type(array_from_list))
print(array_from_list.ndim)
print(array_from_list.shape)

<class 'numpy.ndarray'>
1
(5,)


In [7]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


2D array

In [8]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(type(array_2d))
print(array_2d.ndim)
print(array_2d.shape)

<class 'numpy.ndarray'>
2
(3, 3)


3D array

In [10]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6],
                      [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
type(array_3d)
array_3d.ndim

3

In [22]:
array_3d.shape

(2, 2, 2)

In [25]:
array_3D = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6],
                      [7,8]],

                       [[9, 10],
                       [11, 12]]])
print(array_3D.shape)

(3, 2, 2)


In [27]:
array_3D = np.array([[[1, 2, 3],
                      [3, 4, 5]],

                      [[5, 6, 7],
                      [7, 8, 9]],

                       [[9, 10, 12],
                       [11, 12, 13]]])
print(array_3D.shape)

(3, 2, 3)


inhomogeneous shape of the internal submatrix

In [28]:
array_3D = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6, 7],
                      [7, 8, 9]],

                       [[9, 10, 12],
                       [11, 12, 13]]])
print(array_3D.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

In [29]:
array_3D.dtype

dtype('int64')

In [30]:
array_ = np.array([5, -3.4, 'a', 4.3])
array_

array(['5', '-3.4', 'a', '4.3'], dtype='<U32')

In [31]:
array_.dtype

dtype('<U32')

In [35]:
array_ = np.array([5, -3.4, 4, 4.3])
array_.dtype


dtype('float64')

Itemsize returns the size in bytes of each elements in the array

In [36]:
print("Item size of arr_float: ", array_.itemsize, "bytes")

Item size of arr_float:  8 bytes


data provide a direct buffer to the memory location where the array's data is actually stored

In [50]:
print("data buffer", array_.data)

data buffer <memory at 0x000001B98015DCC0>


Indexing and Slicing

In [51]:
print(array_from_list[2])

3


In [52]:
print(array_2d[2][2])

9


In [53]:
print(array_2d[2, 2])

9


In [55]:
print(array_3d[1,1,1])

8


In [58]:
print(array_3D[2,1,2])

13


In [59]:
print(array_3D[2][1][2])

13


In [60]:
print(array_3D[0,1,0])

3


In [61]:
array_from_list[1:4]

array([2, 3, 4])

In [73]:
array_2d[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [74]:
array_2d[1:3, 1:]

array([[5, 6],
       [8, 9]])

In [75]:
array_3D

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 12],
        [11, 12, 13]]])

In [82]:
array_3D[0:2, 1, 1:]

array([[4, 5],
       [8, 9]])

Methods in NumPy