In [1]:
import numpy as np

Creation of numpy arrays from list

In [5]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [21]:
print(type(array_from_list))
print(array_from_list.ndim)
print(array_from_list.shape)

<class 'numpy.ndarray'>
1
(5,)


In [7]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


2D array

In [8]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(type(array_2d))
print(array_2d.ndim)
print(array_2d.shape)

<class 'numpy.ndarray'>
2
(3, 3)


3D array

In [10]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6],
                      [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
type(array_3d)
array_3d.ndim

3

In [22]:
array_3d.shape

(2, 2, 2)

In [25]:
array_3D = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6],
                      [7,8]],

                       [[9, 10],
                       [11, 12]]])
print(array_3D.shape)

(3, 2, 2)


In [27]:
array_3D = np.array([[[1, 2, 3],
                      [3, 4, 5]],

                      [[5, 6, 7],
                      [7, 8, 9]],

                       [[9, 10, 12],
                       [11, 12, 13]]])
print(array_3D.shape)

(3, 2, 3)


inhomogeneous shape of the internal submatrix

In [28]:
array_3D = np.array([[[1, 2],
                      [3, 4]],

                      [[5, 6, 7],
                      [7, 8, 9]],

                       [[9, 10, 12],
                       [11, 12, 13]]])
print(array_3D.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

In [29]:
array_3D.dtype

dtype('int64')

In [30]:
array_ = np.array([5, -3.4, 'a', 4.3])
array_

array(['5', '-3.4', 'a', '4.3'], dtype='<U32')

In [31]:
array_.dtype

dtype('<U32')

In [35]:
array_ = np.array([5, -3.4, 4, 4.3])
array_.dtype


dtype('float64')

Itemsize returns the size in bytes of each elements in the array

In [36]:
print("Item size of arr_float: ", array_.itemsize, "bytes")

Item size of arr_float:  8 bytes


data provide a direct buffer to the memory location where the array's data is actually stored

In [50]:
print("data buffer", array_.data)

data buffer <memory at 0x000001B98015DCC0>


Indexing and Slicing

In [51]:
print(array_from_list[2])

3


In [52]:
print(array_2d[2][2])

9


In [53]:
print(array_2d[2, 2])

9


In [55]:
print(array_3d[1,1,1])

8


In [58]:
print(array_3D[2,1,2])

13


In [59]:
print(array_3D[2][1][2])

13


In [60]:
print(array_3D[0,1,0])

3


In [61]:
array_from_list[1:4]

array([2, 3, 4])

In [73]:
array_2d[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [74]:
array_2d[1:3, 1:]

array([[5, 6],
       [8, 9]])

In [75]:
array_3D

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 12],
        [11, 12, 13]]])

In [82]:
array_3D[0:2, 1, 1:]

array([[4, 5],
       [8, 9]])

Methods in NumPy

Arithmetic Operations

In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a + b)

print(a - b)

print(a * b)

print(a / b )

print(a ** 2)

print(b // a)

[[11 22]
 [33 44]]
[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]
[[0.1 0.1]
 [0.1 0.1]]
[[ 1  4]
 [ 9 16]]
[[10 10]
 [10 10]]


Transpose 

In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]



Sorting 

In [9]:
arr_1d = np.array([2, 8, 4, 1, 9, 40, 5, 3])
sorted_in_arr = np.sort(arr_1d)
print(sorted_in_arr)

[ 1  2  3  4  5  8  9 40]


In [12]:
arr_2d = np.array([[3, 2, 1],
                   [6, 5, 4]])

sorted_arr_2d = np.sort(arr_2d, axis=1)
print(sorted_arr_2d)

[[1 2 3]
 [4 5 6]]


axis=0 runs vertically down the columns 

axis=1 runs horizontally across the rows

In [13]:
arr_2d = np.array([[3, 2, 1],
                   [6, 5, 4]])

sorted_arr_2d = np.sort(arr_2d, axis=0)
print(sorted_arr_2d)

[[3 2 1]
 [6 5 4]]


argsort()

In [14]:
arr_1d

array([ 2,  8,  4,  1,  9, 40,  5,  3])

In [15]:
sorted_indcies_1D = np.argsort(arr_1d)
print(sorted_indcies_1D)

[3 0 7 2 6 1 4 5]


Ranking in Recommendation Systems

In [20]:
similarity_score = np.array([0.23, 0.85, 0.11, 0.65, 0.91])
sorted_indices = np.argsort(similarity_score)
print(sorted_indices)
top3_items = sorted_indices[-3:][::-1]
print(top3_items)

[2 0 3 1 4]
[4 1 3]


Concatenation Arrays

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))
print(result)

[1 2 3 4 5 6]


In [23]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [5, 6, 7]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


In [24]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[4, 5, 6], [5, 6, 7]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 3 4 5 6]
 [3 4 5 5 6 7]]


Reshape

In [26]:
arr_1d

array([ 2,  8,  4,  1,  9, 40,  5,  3])

In [31]:
arr_2D = arr_1d.reshape(2,4)
print(arr_2D)

[[ 2  8  4  1]
 [ 9 40  5  3]]


In [32]:
arr_2D

array([[ 2,  8,  4,  1],
       [ 9, 40,  5,  3]])

In [34]:
arr_2D = arr_1d.reshape(3,4)
arr_2D

ValueError: cannot reshape array of size 8 into shape (3,4)

Concat ==> pandas [deals with labeled data]

concatenate ==> numpy [array focused]

In [36]:
## Flatten the 2D array to 1D array 
arr_2D.reshape(-1)

array([ 2,  8,  4,  1,  9, 40,  5,  3])

Split()

In [37]:
split_arr = np.split(arr_1d , 4)


In [38]:
split_arr

[array([2, 8]), array([4, 1]), array([ 9, 40]), array([5, 3])]

Statistical Operations : mean, median, mode, standard deviation , min, max, sum

In [39]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_all = np.mean(arr)
print(mean_all)


3.5


In [40]:
mean_axis_0 = np.mean(arr, axis=0) ## axis=0 indicates column-wise
print(mean_axis_0)

[2.5 3.5 4.5]


In [42]:
mean_axis_1 = np.mean(arr, axis=1) ## axis=1 indicates row-wise
print(mean_axis_1)

[2. 5.]


In [43]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

median_all = np.median(arr)
print(median_all)


3.5


np.median => Median 
np.std => standard Deviation 
np.min => Minimum value
np.max => Maximum value
np.sum => sum